# Generated by Django 5.0.4 on 2025-03-22 09:51

import main_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('RPG', 'RPG'), ('Adventure', 'Adventure'), ('Sports', 'Sports'), ('Strategy', 'Strategy')], max_length=100)),
                ('release_year', models.PositiveIntegerField(validators=[main_app.validators.RangeValidator(max_value=2023, message='The release year must be between 1990 and 2023', min_value=1990)])),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[main_app.validators.RangeValidator(max_value=10, message='The rating must be between 0.0 and 10.0', min_value=0)])),
            ],
        ),
    ]
