# Generated by Django 5.0.4 on 2025-03-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('difficulty_level', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('repetitions', models.PositiveIntegerField()),
            ],
        ),
    ]
