# Generated by Django 5.0.4 on 2025-03-14 12:14

import main_app.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_zoodisplayanimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='availability',
            field=main_app.field.BooleanChoiceField(choices=[(1, 'Available'), (0, 'Not Available')], default=True),
        ),
    ]
