# Generated by Django 5.0.4 on 2025-03-10 17:43

from django.db import migrations


def create_unique_brands(apps, schema_editor):
    ShoeModel = apps.get_model('main_app', 'Shoe')
    UniqueBrandsModel = apps.get_model('main_app', 'UniqueBrands')

    unique_brands = ShoeModel.objects.values_list('brand', flat=True).distinct()
    UniqueBrandsModel.objects.bulk_create(UniqueBrandsModel(brand_name=unique_brand) for unique_brand in unique_brands)

def delete_unique_brands(apps, schema_editor):
    UniqueBrandsModel = apps.get_model('main_app', 'UniqueBrands')
    UniqueBrandsModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(
            create_unique_brands,
            reverse_code=delete_unique_brands
        )
    ]
