# Generated by Django 5.0.4 on 2025-03-10 18:00

from django.db import migrations
from django.db.models import Case, When, Value, CharField


def update_age_group(apps, schema_editor):
    PersonModule = apps.get_model('main_app', 'Person')

    PersonModule.objects.update(
        age_group=Case(
            When(age__lte=12, then=Value('Child')),
            When(age__lte=17, then=Value('Teen')),
            default=Value('Adult'),
            output_field=CharField()
        )
    )


def reverse_update_age_group(apps, schema_editor):
    PersonModule = apps.get_model('main_app', 'Person')
    default_age_group = PersonModule._meta.get_field('age_group').default
    PersonModule.objects.update(age_group=default_age_group)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(
            update_age_group,
            reverse_code=reverse_update_age_group
        )
    ]
