# Generated by Django 5.0.4 on 2025-03-10 18:05

from django.db import migrations
from django.db.models import Case, When, Value, CharField


def update_rarity(apps, schema_editor):
    ItemModule = apps.get_model('main_app', 'Item')
    ItemModule.objects.update(
        rarity=Case(
            When(price__lte=10, then=Value('Rare')),
            When(price__lte=20, then=Value('Very Rare')),
            When(price__lte=30, then=Value('Extremely Rare')),
            default=Value('Mega Rare'),
            output_field=CharField()
        )
    )


def revere_update_rarity(apps, schema_editor):
    ItemModule = apps.get_model('main_app', 'Item')
    default_rarity = ItemModule._meta.get_field('rarity').default
    ItemModule.objects.update(rarity=default_rarity)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(
            update_rarity,
            reverse_code=revere_update_rarity
        )
    ]
