# Generated by Django 5.0.4 on 2025-03-10 18:11

from django.db import migrations
from django.db.models import Case, When, Value, CharField
from django.db.models.functions import Length


def update_price(apps, schema_editor):
    Smartphone = apps.get_model('main_app', 'Smartphone')
    Smartphone.objects.update(price=Length('brand') * 120)


def reverse_update_price(apps, schema_editor):
    Smartphone = apps.get_model('main_app', 'Smartphone')
    default_price = Smartphone._meta.get_field('price').default
    Smartphone.objects.update(price=default_price)


def update_category(apps, schema_editor):
    Smartphone = apps.get_model('main_app', 'Smartphone')
    Smartphone.objects.update(
        category=Case(
            When(price__gte=750, then=Value('Expensive')),
            default=Value('Cheap'),
            output_field=CharField()
        ))


def reverse_update_category(apps, schema_editor):
    Smartphone = apps.get_model('main_app', 'Smartphone')
    default_category = Smartphone._meta.get_field('category').default
    Smartphone.objects.update(category=default_category)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(
            update_price,
            reverse_code=reverse_update_price
        ),
        migrations.RunPython(
            update_category,
            reverse_code=reverse_update_category
        )
    ]
